### ISSUE TITLE
APIError: GitHub event 'schedule' is not supported.

### ISSUE THREAD

**Issue by mvdschee** [denoland/deployctl#110]
Hello while building my project in GitHub actions for a custom build process I ran in to a problem with deployctl failing if the deployment was trigger on a schedule in GitHub actions
<img width="983" alt="Screenshot 2022-04-08 at 11 13 28" src="https://user-images.githubusercontent.com/26795741/162355865-8ab0c0a4-f741-448c-9056-cd7ae6bb4774.png">

the CD.yaml I use
```yaml
name: Continuous Deployment

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    schedule:
        # every hour
        - cron: '0 * * * *'
    workflow_dispatch:

jobs:
    ci:
        runs-on: ${{ matrix.os }}
        permissions:
            id-token: write
            contents: read

        strategy:
            matrix:
                os: [ubuntu-latest]
                deno-version: [1.20.4]

        steps:
            - name: Git Checkout Deno Module
              uses: actions/checkout@v2

            - name: Use Deno Version ${{ matrix.deno-version }}
              uses: denolib/setup-deno@v2
              with:
                  deno-version: ${{ matrix.deno-version }}

            - name: Run build 👷
              run: make build

            - name: Upload to Deno Deploy
              uses: denoland/deployctl@v1
              with:
                  project: '******'
                  entrypoint: './main.ts'
```

Looking at the code why this would happen I didn't came any closer then [`/deployctl/blob/main/action/index.js`](https://github.com/denoland/deployctl/blob/b5d4c4c6a9b30cbfedc480dcee8d8c57775bce9b/action/index.js#L103) where you start defining the the switch case for the event types. Either the event type has an extra step which is not defined or the API it self gets an type it's confused about.

Here is a build that was triggered on a push that did succeed
<img width="983" alt="Screenshot 2022-04-08 at 11 24 17" src="https://user-images.githubusercontent.com/26795741/162356827-271df3cd-972d-40c0-a397-f73ba60a558d.png">
