### ISSUE TITLE
deploying statically generated site

### ISSUE THREAD

**Issue by lambtron** [denoland/deployctl#120]
would be cool if we could allow github action yaml file to look like this:

```
- uses: denoland/deployctl@v1
        with:
          project: example-deno-eleventy
          static: _site
```

instead of:

```
- uses: denoland/deployctl@v1
        with:
          project: example-deno-eleventy
          entrypoint: https://deno.land/std@0.131.0/http/file_server.ts
          root: _site
```
