### ISSUE TITLE
action: Failed to open entrypoint file (ENOENT)

### ISSUE THREAD

**Issue by dwisiswant0** [denoland/deployctl#126]
When I deploy a single file typescript, I get the error as `Failed to open entrypoint file at 'file:///home/runner/work/REPOSITORY/REPOSITORY/server.js': ENOENT: no such file or directory, lstat '/home/runner/work/REPOSITORY/REPOSITORY/server.js'` which is the file is in the root directory (so I don't need to supply `root` input). Why do I get this kind of behavior?

Here's my workflow file:
```yaml
name: Build & Deploy

on:
  push:
    paths:
      - "server.ts"
      - "**.md"
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      # MY BUILD STEPS HERE

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: REPOSITORY
          entrypoint: ./server.js
```

**Comment by dwisiswant0** [comment]
As the error message that left behind:
```
(node:2976) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

I guess the action should support arbitrary flags input.

**Comment by dwisiswant0** [comment]
I think it's because of #121?

**Comment by kt3k** [comment]
Deno Deploy builds your typescript by default. You don't need to build your script on your own. Just specify `server.ts` as entrypoint.

> (node:2976) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

This warning looks like from node.js. Does your server.ts script work with `deno`? (like `deno run --allow-net server.ts`)

**Comment by dwisiswant0** [comment]
@kt3k - yes it's work by my side, and I didn't use any Deno unstable API.

**Comment by kt3k** [comment]
@dwisiswant0 What happens if you specify `entrypoint: ./server.ts` instead of `entrypoint: ./server.js`?

BTW why do you build your script on your own?

**Comment by marcosadriano05** [comment]
This happens to me too:
![image](https://user-images.githubusercontent.com/71355331/177868735-755ccea3-778c-4e9a-94f4-f14e5c87f8ed.png)

My yml file:
```
deploy:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: marcosadriano05-delivery
          entrypoint: ./src/main/server.ts
```
