### ISSUE TITLE
Use DENO_DEPLOYMENT_ID in github action???

### ISSUE THREAD

**Issue by RickCogley** [denoland/deployctl#149]
Hi - is there a way to get DENO_DEPLOYMENT_ID so that it can be used in a later step in a GH workflow? 

I'm trying this sort of thing: 

~~~~~
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: logr-cogley-info # the name of the project on Deno Deploy
          entrypoint: https://deno.land/std@0.140.0/http/file_server.ts
          root: public # Where the built HTML/CSS/JS files are located.
        env:
          LALALA: Deno.env.get("DENO_DEPLOYMENT_ID")
~~~~~

**Comment by magurotuna** [comment]
Yes, after the deployment is complete, the deployctl action set the deployment ID so you can use it later.
Suppose we have the workflow file that looks like:

```yaml
name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "my-awesome-project"
          entrypoint: "./main.ts"
```

then we can access the deployment_id via `${{ steps.<deployctl_step_id>.outputs.deployment-id }}`, like as follows:

```diff
name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Upload to Deno Deploy
+       id: deploy
        uses: denoland/deployctl@v1
        with:
          project: "my-awesome-project"
          entrypoint: "./main.ts"
+
+     - name: print deployment_id
+       run: echo ${{ steps.deploy.outputs.deployment-id }}
```

Hope it helps :)
