### ISSUE TITLE
Using http2 and caching in static websites

### ISSUE THREAD

**Issue by YonatanKra** [denoland/deployctl#161]
This is my setup:
```
        uses: denoland/deployctl@v1
        with:
          project: {ENV.PROJECt}
          root: dist/apps/docs
          entrypoint: https://deno.land/std@0.135.0/http/file_server.ts
```
1. Is there a way to force http2 connection?
2. Is there a way to set caching policy?
Thanks :)
