### ISSUE TITLE
Actions ignores working-directory settings

### ISSUE THREAD

**Issue by aya-eiya** [denoland/deployctl#250]
## What

In a mono-repository (or sub directory structure) project, the working-directory setting is not respected for 'denoland/deployctl.'

## Cases

Assuming the project directories are structured as follows:

```
my-repo
  - user-web  <- deploy target ( fresh web app project )
  - client-web
  - batches
  - mobile-apps
```

A straightforward deploy.yml for building and deploying the deno-fresh project would typically look like this:

```yaml
jobs:
  deploy-user-web-development:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./user-web

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build step
        run: 'deno task build' # 📝 Update the build command(s) if necessary

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: 'user-web' # 📝 Update the deploy project name if necessary
          entrypoint: './main.ts' # 📝 Update the entrypoint if necessary
```

## Errors

However, the action stops during the deployment phase with the following error:

```
The deployment failed: ISOLATE_INTERNAL_FAILURE
```

> https://github.com/aya-eiya/deno-practice/actions/runs/7723829587/job/21057968805#step:5:248

## Causes

The issue arises when attempting to set a subdirectory that is the directory for the project to be deployed as the working directory with actions related to 'denoland/deployctl.' This action is not designed to respect the working-directory setting and always  deploys the repository's root directory, leading to a deployment error.

## Expected

When you set the working-directory in GitHub Actions, the expected behavior is that the deployment should operate within that directory rather than ignoring the setting.

## Workaround

You can set the subdirectory containing the project to with.root parameter to solve the error.

But I feel like the "root" setting seems to be for "deploy root" rather than "project root", and the working-directory is as the "project directory" is more like straightforward in this case.
