### ISSUE TITLE
`deployctl deploy` on CircleCI errors out

### ISSUE THREAD

**Issue by lambtron** [denoland/deployctl#262]
my circleci `config.yml`:

```yml
version: 2.1
jobs:
  build_and_deploy:
    docker:
      - image: denoland/deno:alpine
    steps:
      # Clone repo
      - checkout
      # Replace this with steps to deploy to users
      - run:
          name: install deployctl
          command: deno install -qArf https://deno.land/x/deploy/deployctl.ts 
      - run:
          name: deploy project
          command: deployctl deploy --token=$DENO_DEPLOY_TOKEN hello.ts
workflows:
  example:
    jobs:
      - build_and_deploy
```

and when i run it

```
#!/bin/sh -eo pipefail
deployctl deploy --token=$DENO_DEPLOY_TOKEN hello.ts
-1C[-1C[-1C[-1C[-1C[-1C[-1C[-1C[-1C[-1C[-1C[-1C[-1C[-1C[-1C[-1C[-1C[-1C[-1C[-1C[-1C[-1C[-1C[-1C[-1C[-1C[-1C[-1C[-1C
```
ad infinitum.

but i can confirm that `deployctl` is installed properly and the `DENO_DEPLOY_TOKEN` is set.
