### ISSUE TITLE
Support setting env variables in GH action

### ISSUE THREAD

**Issue by arnauorriols** [denoland/deployctl#297]
Integrate with GH secrets?

**Comment by csvn** [comment]
This would be very helpful! I'm not sure what you mean by "Integrate with GH secrets", but if there was an input that could handle a pre-defined syntax for secrets, it would be easy to include manually, right?

```yml
    with:
      env: |
        SHA=${{ github.sha }}
        MY_SECRET=${{ secrets.MY_SECRET }}
```

I was hoping to include some metadata from the current build as environment variables to the deploy, and it would be nice if this could be achieved with the action, and not just with `deployctl deploy`.
