### ISSUE TITLE
The deploy action isn't resolving the entrpoint path correctly

### ISSUE THREAD

**Issue by justinmchase** [denoland/deployctl#363]
My workflow is pretty simple:

```yml
name: Deploy
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: example
          entrypoint: main.ts
```

But it errors saying it can't find `file://src/main.ts`

![Image](https://github.com/user-attachments/assets/eb9b30e3-9c6a-4a84-aa57-bafdbfd3a001)

My main file is in the root directory...

![Image](https://github.com/user-attachments/assets/e4878a57-0c12-4b0b-a066-a5a485d13bba)

What's going on?

I've tried setting `root: .` but it had no effect.
